name: ci
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$(cat docker-name.txt):$(docker-tag.txt) .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: push api
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/$(cat docker-name.txt):$(docker-tag.txt)