name: ci
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push 
        run: cd $(cat current) && \
            sed -z 's/\(.*\)}\(.*\)/\1,"data-root":"\/mnt\/docker" }\2/' /etc/docker/daemon.json && \
            systemctl restart docker && \
            docker buildx build --push -t ${{ secrets.DOCKERHUB_USERNAME }}/$(cat docker-name.txt):$(cat docker-tag.txt) .