name: push-image
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'docker image to download'
        required: true
        type: string
      target:
        description: 'target file path'
        required: true
        type: string
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup
        run: sudo -E bash scripts/docker_save.sh
        env:
          MODELSCOPE_TOKEN: ${{ secrets.MODELSCOPE_TOKEN }}
          DOKCER_IMAGE: ${{ inputs.image }}
          DOCKER_TARGET: ${{ inputs.target }}